<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKIRSxxj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKIRSxxj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKIRSxxj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKIRSxxj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKIRSxxj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KIRSxxj',
    'container.build_id' => '8812edfc',
    'container.build_time' => 1645668776,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKIRSxxj');
